# .github/workflows/main.yml
name: Notify Minecraft Server on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install mcrcon
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential
          git clone https://github.com/Tiiffi/mcrcon.git
          cd mcrcon
          make
          sudo install mcrcon /usr/local/bin

      - name: Send RCON Command
        env:
          RCON_HOST: ${{ secrets.RCON_HOST }}
          RCON_PORT: ${{ secrets.RCON_PORT }}
          RCON_PASSWORD: ${{ secrets.RCON_PASSWORD }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          mcrcon -H "$RCON_HOST" -P "$RCON_PORT" -p "$RCON_PASSWORD" "say [ThexOS] Update Available: $SHORT_SHA"
